apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::596822259792:role/eksctl-clean-slate-api-nodegroup-NodeInstanceRole-1AQEUPC51OVCP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::596822259792:role/UdacityFlaskDeployCBKubectlRoleTwo
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-30T16:44:05Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2020-11-30T16:44:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1811"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f5ba5c8b-a9a1-40fc-8e90-9b8890a3e049
